package controller;

import ioModule.DebugMessager;

import java.util.ArrayList;

import controller.MainController;
import store.Course;
import store.Section;


public class ListHandler {
	static String title = "ListHandler : ";
	public ListHandler(){
		
	}
	/**
	 * Try to found out the priority and conflict number of each section
	 * @param list courselist generated by the Main
	 */
	public void listformat(ArrayList<Course> list){
		DebugMessager.debug(title+"\tListHandler Start setting priority");
		int maxSecNum=0;
		Boolean SimpleCase = true; 
		for(Course c : list){ // get the largest Section nums => used to determine the priority
			/* if the Max. Section of ALL course < 10 the priority will be 2 digit
			 * if the number is >=10 and <100 the priority will be 2 digit
			 * the most left number is refer to the course, that means section for same course will have same value
			 */
			if(maxSecNum<c.SectionNum()){
				maxSecNum=c.SectionNum(); 
			}
		}
		DebugMessager.debug(title+"Largest Section Num = "+maxSecNum);
		int places = (int) (Math.floor(Math.log10(maxSecNum))+1);
		DebugMessager.debug(title+"Places need = "+places);
		int courseNum = list.size();
		for(int i=0;i<courseNum;i++){ // init the Priority table
			Course c = list.get(i);
			DebugMessager.debug(title+"ListHandler handling Course "+c.getCourseID());
			ArrayList<Section> seclist=c.getSec();
			int tempPriority=(courseNum-c.getPriority()+1)*((int)Math.pow(10, places)) + seclist.size();
			for(int j=0;j<seclist.size();j++){
				Section s = seclist.get(j);
				DebugMessager.debug(title+"\tListHandler handling Section "+s.getSectionID());
				s.setPriority(tempPriority--);
				int CourseConflict = ConflictDetector.run(list, i,s);
				
				s.setCourseConflict(CourseConflict);
				DebugMessager.debug(title+"\tListHandler Section "+s.getSectionID()+", priority = "+tempPriority);
			}
			if(c.getSecNumMinConflict()==courseNum) SimpleCase = false;
		}
		if(courseNum<=2) SimpleCase=true;
		MainController.setSimpleHandler(SimpleCase);
		DebugMessager.debug(title+"\tListHandler End.");
	}

}
