package Controller;

import ioMoudle.DebugMessager;

import java.util.ArrayList;

import store.Course;
import store.Section;

public class ListHandler {
	
	public ListHandler(){
		
	}
	/**
	 * Try to found out the priority and conflict number of each section
	 * @param list courselist generated by the Main
	 */
	public void listformat(ArrayList<Course> list){
		DebugMessager.debug("\tPriorityHandler Start setting priority");
		int maxSecNum=0;
		for(Course c : list){ // get the largest Section nums => used to determine the priority
			/* if the Max. Section of ALL course < 10 the priority will be 2 digit
			 * if the number is >=10 and <100 the priority will be 2 digit
			 * the most left number is refer to the course, that means section for same course will have same value
			 */
			if(maxSecNum<c.SectionNum()){
				maxSecNum=c.SectionNum(); 
			}
		}
		DebugMessager.debug("Largest Section Num = "+maxSecNum);
		int places = (int) (Math.floor(Math.log10(maxSecNum))+1);
		DebugMessager.debug("Places need = "+places);
		int courseNum = list.size();
		for(int i=0;i<courseNum;i++){ // init the Priority table
			Course c = list.get(i);
			int tempPriority=(courseNum-c.getPriority()+1)*((int)Math.pow(10, places));
			DebugMessager.debug("PriorityHandler handling Course "+c.getCourseID());
			ArrayList<Section> seclist=c.getSec();
			for(int j=0;j<seclist.size();j++){
				Section s = seclist.get(j);
				DebugMessager.debug("\tPriorityHandler handling Section "+s.getSectionID());
				s.setPriority(++tempPriority);
				s.setCourseConflict(ConflictDetector.run(list, i,s));
				DebugMessager.debug("\tPriorityHandler Section "+s.getSectionID()+", priority = "+tempPriority);
			}
		}
		DebugMessager.debug("\tPriorityHandler End.");
	}

}
